version: "2.1"

services:
  web:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/karaoke_development
      - PORT=3000
    links:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app

  db:
    image: postgres
    expose:
      - 5432
