version: "2.1"

services:
  frontend:
    command: yarn start
    image: node
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app

  web:
    build: ./server
    environment:
      - PORT=3001
    expose:
      - 3001
    ports:
      - 3001:3001
    volumes:
      - ./server:/app
    working_dir: /app
