version: "2.1"

services:
  frontend:
    command: yarn start
    image: node
    ports:
      - 3001:3000
    volumes:
      - .:/app
    working_dir: /app
    environment:
      CHOKIDAR_USEPOLLING: 'true'

  web:
    build: ./server
    environment:
      - PORT=3000
      - PASSWORD
      - RAILS_ENV=development
    expose:
      - 3001
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
    working_dir: /app

  spec:
    build: ./server
    volumes:
      - ./spec:/spec
