version: "2.1"

services:
  db:
    image: postgres
    expose:
      - 5432

  frontend:
    command: yarn start
    image: node
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    working_dir: /app

  web:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/karaoke_development
      - PORT=3001
    links:
      - db
    expose:
      - 3001
    ports:
      - 3001:3001
    volumes:
      - .:/app
    working_dir: /app
